name: 🗞 Daily Top HackerNews

on:
  schedule:
    - cron: '0 9 * * *' # Every day at 9am
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: daily-top-hackernews
      id: hackernews
      uses: ./ # Uses an action in the root directory
      with:
        news: 5